# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nam.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputBox = QtWidgets.QLineEdit(self.centralwidget)
        self.inputBox.setObjectName("inputBox")
        self.verticalLayout.addWidget(self.inputBox)
        self.cmdsBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.cmdsBox.setObjectName("cmdsBox")
        self.verticalLayout.addWidget(self.cmdsBox)
        self.runBtn = QtWidgets.QPushButton(self.centralwidget)
        self.runBtn.setObjectName("runBtn")
        self.verticalLayout.addWidget(self.runBtn)
        self.outputBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.outputBox.setAcceptRichText(False)
        self.outputBox.setObjectName("outputBox")
        self.verticalLayout.addWidget(self.outputBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearBtn.setObjectName("clearBtn")
        self.horizontalLayout.addWidget(self.clearBtn)
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setObjectName("resetBtn")
        self.horizontalLayout.addWidget(self.resetBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "НАМ"))
        self.inputBox.setPlaceholderText(_translate("MainWindow", "Входная строка"))
        self.cmdsBox.setPlaceholderText(_translate("MainWindow", "Команды через точку с запятой. Пустые команды недопустимы."))
        self.runBtn.setText(_translate("MainWindow", "Выполнить"))
        self.outputBox.setPlaceholderText(_translate("MainWindow", "Здесь будет вывод"))
        self.clearBtn.setText(_translate("MainWindow", "Очистить вывод"))
        self.resetBtn.setText(_translate("MainWindow", "Сбросить всё"))
